version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
      - ./docker-start.sh:/usr/local/bin/start
    entrypoint: /usr/local/bin/start
    environment:
      CONTAINER_ROLE: app
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./docker-start.sh:/usr/local/bin/start
    environment:
      CONTAINER_ROLE: scheduler
    entrypoint: /usr/local/bin/start
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./docker-start.sh:/usr/local/bin/start
    environment:
      CONTAINER_ROLE: queue
    entrypoint: /usr/local/bin/start